Name=['redwan', 'sanjida','nishi','turzo']
print(Name[-1].title())
print(Name)
print(Name[3].title()) 
Name.append('simla')
print(Name)
Name.insert(1,'haga')
print(Name)
Name.sort(reverse=True)
print(Name)
Name.sort()
print(Name)
print(sorted(Name))
print(Name)
Name.reverse()
print(Name)
print(len(Name))